### ISSUE TITLE
The number of data mismatch?

### ISSUE THREAD

**Issue by HBioquant** [kad-ecoli/mmCIF2BioLiP#5]
Hi, chengxin. when I used the perl script (https://zhanggroup.org/BioLiP/download/download_all_sets.pl) to download the whole BioLip dataset, results in 'receptor' directory has 404210 pdb files, with 592847 pdb files in 'ligand' directory, while BioLip website (https://zhanggroup.org/BioLiP/index.cgi) displays ligand number is 828987 (sum of regular ligands, metal ions, DNA, RNA and peptides). Why is there such a datapoint number difference? (I repeated the script and downloaded it three times, and the result was the same.) Another question is how BioLip labels regular ligands, metal ligands, peptide ligands, DNA/RNA ligands, I noticed that the peptide ligands can be recognized by the 'peptide' string in the pdb file name, and the DNA/RNA ligands can be recognized by the 'dna'/'rna' in the pdb file name. Is that enough to tell them apart? (excuse me for not looking through your code to see how you name files)

**Comment by kad-ecoli** [comment]
829k is the number of protein-ligand interactions, not the number of ligands. A ligand can interact with multiple proteins, resulting in multiple ligand-protein interactions.

**Comment by kad-ecoli** [comment]
the peptide ligands can be recognized by the 'peptide' string in the pdb file name, and the DNA/RNA ligands can be recognized by the 'dna'/'rna' in the pdb file name. That is sufficient to differentiate polymer ligands.
