### ISSUE TITLE
script/rsyncPDB.sh is not working

### ISSUE THREAD

**Issue by suice07** [kad-ecoli/mmCIF2BioLiP#6]
Hello, dear chengxin. I am trying to download the whole BioLip dataset following the instructions, but when I excute script/rsyncPDB.sh, the downloading is actually not getting started. am I missing something? or is there some other requirements should be satisfied first? I am trying to downlowd using download/download_all_sets.pl instead, will it be the same ?

**Comment by kad-ecoli** [comment]
download_all_set.pl will directly download currated data from http://zhanggroup.org/BioLiP2. 

If you follow readme.md and use rsyncPDB.sh etc you are trying to download and curate raw data from the PDB database. The latter will be far more  time consuming.
