### ISSUE TITLE
Typos at README.md

### ISSUE THREAD

**Issue by yuyuan871111** [kad-ecoli/mmCIF2BioLiP#7]
Typos: 
* [Readme.md line 121](https://github.com/kad-ecoli/mmCIF2BioLiP/blob/8ab340bad28f5d66d590e4d6819bd8c2b0cfe818/README.md?plain=1#L121C1-L121C1) should be step  7 instead of step 6.
* [Readme.md line 130](https://github.com/kad-ecoli/mmCIF2BioLiP/blob/8ab340bad28f5d66d590e4d6819bd8c2b0cfe818/README.md?plain=1#L130C1-L130C1) should be step  8 instead of step 7.

**Comment by kad-ecoli** [comment]
fixed with https://github.com/kad-ecoli/mmCIF2BioLiP/commit/9b448dd69b182676927a27beafe59c4593cf5174
